### ISSUE TITLE
iOS app - always connects to port 5000 ?

### ISSUE THREAD

**Issue by bakman2** [holesail/holesail#12]
As subject, is this port correct ?

I have ollama running on my mac
I start holesail: `holesail --live 11434` - which is the port for ollama

In iOS app - i scan QR - it says "Securely connected and running on 5000" - is this correct ? Where does the 5000 come from ?

I use enchanted (chat app for ollama) - it cannot find the server on both 5000 and 11434  (yes it is accessible outside local host).

**Comment by bakman2** [comment]
Testing a bit more, it seems to function properly for things other than ollama (quite cool stuff).

**Comment by supersuryaansh** [comment]
@bakman2 Thanks for pointing it out. I will test this with Ollama. In the meantime, if you are on an iPhone, instead of opening Safari, can you click on the "Securely connected and running on port 5000" orange button? It will open an integrated browser, and check if that works.

If it still does not work, can you also try passing the host parameter while setting the port for Ollama live, something like:
holesail --live 11434 --host localhost

Make sure the host is correct as 127.0.0.1 is different from localhost which is different from 0.0.0.0 and it will matter to Holesail which one you use.

**Comment by bakman2** [comment]
@supersuryaansh  yeah indeed the orange button shows it is running, but the enchanted app somehow cannot connect (i have provided the same url) - maybe it is related to some timeout  for that app specifically, not sure.

**Comment by supersuryaansh** [comment]
@bakman2 Okay, I will test it and let you know.
