### ISSUE TITLE
segmentation fault (alpine linux)

### ISSUE THREAD

**Issue by dipunm** [holesail/holesail#2]
I am running an Alpine Linux server and attempting to connect from a Arch Linux laptop.

Alpine:
```bash
$ holesail --connector=hello --live 3001
```

Arch:
```bash
$ holesail --connect hello --port 8080
```

When I visit `http://localhost:8080`, The Alpine server reports "Segmentation fault" and exits.

There is no other information.

I can provide more debug information as required upon request, but I think the issue may be due to running on an Alpine Server.

**Comment by supersuryaansh** [comment]
@dipunm can you paste the exact error here.

**Comment by supersuryaansh** [comment]
@dipunm Can you check your Nodejs version and paste the screenshot of the error as well.

**Comment by dipunm** [comment]
![image](https://github.com/holesail/holesail/assets/5099980/0e867568-4d74-4c21-a29a-fd5b7c9a6dbd)

Here is everything.

- The transparent terminal is my own machine, it uses node v20.11.0
- The other terminal is my remote Alpine Linux, it uses node v20.12.1
- It is only when I try to make a http connection through the tunnel that the program exits on Alpine.
- The error is unfortunately very unhelpful, I gave the whole error message, but now you can see it too.

**Comment by supersuryaansh** [comment]
@dipunm Thanks that helps, we have confirmed that this bug exists and now working to find and fix this. Will let you know when it is fixed.

**Comment by dipunm** [comment]
Amazing. Anything else I can do to help, let me know.

**Comment by utkarshpayal** [comment]
@dipunm sure

**Comment by supersuryaansh** [comment]
@dipunm I finally got my hands on Alpine Linux, looks like the issue is with Sodium-native which wouldn't compile on Alpine Linux.

**Comment by supersuryaansh** [comment]
@dipunm On Alpine Linux you need to perform a few additional steps before installing Holesail so that sodium-native builds correctly.

Run the following command and install these apks:

1. apk add nodejs npm
2. apk add python3
3. apk add autoconf
4. apk add automake
5. apk add make
6. apk add build-base

Then install holesail:
npm i holesail -g

and you should be good to go.

**Comment by dipunm** [comment]
I spun up a brand new VM with alpine and followed only the steps you gave after logging in as root for the first time.

I still get the error:
![image](https://github.com/holesail/holesail/assets/5099980/3ad2d5e8-ce06-4596-b4bc-cfbd18a7bfb4)

The image I am using is: `alpine-virt-3.19.1-x86_64.iso`

**Comment by dipunm** [comment]
On local (Arch Linux) I am using holesail version 1.5.2
On Alpine (as the server) I am using holesail version 1.5.2

**Comment by dipunm** [comment]
@supersuryaansh please unclose :pray:

**Comment by dipunm** [comment]
Unsure if this is useful, but after running: `npm list -g -a` I saw mention of an error log, and this is what it shows in that log file:

![image](https://github.com/holesail/holesail/assets/5099980/55ae9db0-acfc-46dc-935f-0789e5e3e1b6)

**Comment by dipunm** [comment]
This is literally everything I ran since spinning up the VM:

![image](https://github.com/holesail/holesail/assets/5099980/4e541bbd-69f8-49c0-816b-df1bf98c98b2)

I'm taking screen grabs because the terminal emulator (I'm running all of this on proxmox) doesn't allow me to select text :shrug:

**Comment by supersuryaansh** [comment]
@dipunm Alpine does not have libc and hence the errors, it is failing due to sodium-native. You can use a container with libc support or follow these instructions to use holesail on Alpine:
1. apk add git
2. git clone https://github.com/holesail/holesail.git
3. cd holesail
4. apk add nodejs npm
5. apk add python3
6. apk add autoconf
7. apk add automake
8. apk add make
9. apk add build-base

Then build from source with this:
npm i --build-from-source --foreground-scripts

**Comment by dipunm** [comment]
I can confirm that the steps above worked.

I did have to run the program using:

```
npm index.js .....
```

instead of 

```
holesail ...
```

Just for completeness of instructions for any future readers.

Thanks for your investigation and help on this.
